import { Product } from './types/Product'

export const sampleProducts: Product[] = [
  {
    name: 'Nike Slim shirt',
    slug: 'nike-slim-shirt',
    category: 'Shirts',
    image: '/p1.jpg',
    price: 120,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 10,
    description: 'High quality shirt',
  },
  {
    name: 'Adidas Fit shirt',
    slug: 'adidas-fit-shirt',
    category: 'Shirts',
    image: '/p2.jpg',
    price: 100,
    countInStock: 20,
    brand: 'Adidas',
    rating: 4.0,
    numReviews: 10,
    description: 'High quality shirt',
  },

  {
    name: 'Lacoset Free Pants',
    slug: 'lacoste-free-pants',
    category: 'Pants',
    image: '/p3.jpg',
    price: 220,
    countInStock: 0,
    brand: 'Lacoste',
    rating: 4.8,
    numReviews: 17,
    description: 'High quality shirt',
  },
  {
    name: 'Nike Slim Pants',
    slug: 'nike-slim-pants',
    category: 'Pants',
    image: '/p4.jpg',
    price: 78,
    countInStock: 15,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 14,
    description: 'High quality shirt',
  },
]
